export async function exportArtifactToMarkdown(asset: any): Promise<string> {
  let md = `# ${asset.title}\n\n`;

  if (asset.type === "document") {
    // If we have plain text fallback
    if (typeof asset.content?.body?.content === "string") {
      md += asset.content.body.content;
    } else {
      md += JSON.stringify(asset.content, null, 2);
    }
  } else if (asset.type === "quiz") {
    asset.content?.questions?.forEach((q: any, i: number) => {
      md += `### ${i + 1}. ${q.q}\n`;
      q.options?.forEach((opt: string, j: number) => {
        md += `- [${q.correctIndex === j ? 'x' : ' '}] ${opt}\n`;
      });
      md += `\n`;
    });
  } else if (asset.type === "flashcards") {
    asset.content?.forEach((card: any, i: number) => {
      md += `**Q:** ${card.front}\n**A:** ${card.back}\n\n---\n\n`;
    });
  } else if (asset.type === "summary") {
    if (asset.content?.tldr) md += `**TL;DR:** ${asset.content.tldr}\n\n`;
    asset.content?.sections?.forEach((sec: any) => {
      md += `## ${sec.heading}\n`;
      sec.points?.forEach((p: string) => md += `- ${p}\n`);
      md += `\n`;
    });
  } else {
    md += JSON.stringify(asset.content, null, 2);
  }

  md += `\n\n---\n*Generated by EduOS*`;
  return md;
}
